apiVersion: v1
kind: Secret
metadata:
  name: shirods-secrets
  namespace: shirods
type: Opaque
stringData:
  API_BEARER_TOKEN: "replace-with-strong-token"
  API_ACL_ADMIN_TOKENS: "replace-admin-token"
  API_ACL_PUBLISH_TOKENS: "replace-publish-token"
  API_ACL_READ_TOKENS: "replace-read-token"
  NATS_USER: ""
  NATS_PASSWORD: ""
  NATS_TOKEN: ""
  ETCD_USER: ""
  ETCD_PASSWORD: ""
  CASSANDRA_USER: ""
  CASSANDRA_PASSWORD: ""
