apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shirods-controlplane
  namespace: shirods
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - shirods
  selector:
    matchLabels:
      app: shirods-controlplane
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
